services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: holywars
      POSTGRES_USER: holywars
      POSTGRES_PASSWORD: holywars
    ports:
      - "5432"
    volumes:
      - holywars-postgres:/var/lib/postgresql/data
volumes:
  holywars-postgres:
