create table player (
    id bigint not null primary key,
    name varchar(255),
    gold_updated_at timestamp(6) with time zone
);

create table island (
    id bigint not null primary key,
    luxury_resource varchar(255),
    name varchar(255),
    x integer not null,
    y integer not null
);

create table island_plot (
    id bigint generated by default as identity primary key,
    number integer not null,
    occupant_town_id bigint,
    island_id bigint not null references island(id),
    constraint uk_island_plot_island_id_number unique (island_id, number)
);

create table town (
    id bigint not null primary key,
    island_id bigint not null,
    name varchar(255),
    owner_id bigint not null,
    plot_number integer not null,
    luxury_resource varchar(255),
    resources_updated_at timestamp(6) with time zone
);

create table building_slot (
    id bigint generated by default as identity primary key,
    building_level integer,
    building_type varchar(255),
    construction_finishes_at timestamp(6) with time zone,
    construction_started_at timestamp(6) with time zone,
    construction_type varchar(255),
    kind varchar(255),
    position integer not null,
    required_town_hall_level integer not null,
    town_id bigint not null references town(id),
    constraint uk_building_slot_town_id_position unique (town_id, position)
);
