CREATE TABLE world (id INTEGER PRIMARY KEY CHECK (id = 1), grid_width INTEGER NOT NULL, grid_height INTEGER NOT NULL);
CREATE TABLE island (id INTEGER PRIMARY KEY, world_id INTEGER NOT NULL REFERENCES world(id), x INTEGER NOT NULL, y INTEGER NOT NULL, name TEXT NOT NULL, luxury_resource TEXT NOT NULL, UNIQUE (world_id, x, y));
CREATE TABLE city_plot (id INTEGER PRIMARY KEY AUTOINCREMENT, island_id INTEGER NOT NULL REFERENCES island(id), number INTEGER NOT NULL, free INTEGER NOT NULL DEFAULT 1, UNIQUE (island_id, number));
