create table town_plot (
    id bigint generated by default as identity primary key,
    building_level integer,
    building_type varchar(255),
    construction_finishes_at timestamp(6) with time zone,
    construction_started_at timestamp(6) with time zone,
    construction_type varchar(255),
    kind varchar(255),
    position integer not null,
    required_town_hall_level integer not null,
    town_id bigint not null references town(id),
    constraint uk_town_plot_town_id_position unique (town_id, position)
);

insert into town_plot (building_level, building_type, construction_finishes_at, construction_started_at, construction_type, kind, position, required_town_hall_level, town_id)
select building_level, building_type, construction_finishes_at, construction_started_at, construction_type, kind, position, required_town_hall_level, town_id
from building_slot
order by town_id, position;

drop table building_slot;
