spring.web.resources.static-locations=file:${user.home}/.local/share/holy-wars/dev-assets/,classpath:/static/
holywars.town-scene.width=1920
holywars.town-scene.height=1200
holywars.town-scene.plots[1]=928,537,172
holywars.town-scene.plots[2]=952,387,172
holywars.town-scene.plots[3]=694,532,172
holywars.town-scene.plots[4]=1095,493,172
holywars.town-scene.plots[5]=895,671,172
holywars.town-scene.plots[6]=1054,631,172
holywars.town-scene.plots[7]=693,652,172
holywars.town-scene.plots[8]=1253,610,172
holywars.town-scene.plots[9]=1251,451,172
holywars.town-scene.plots[10]=534,491,172
holywars.town-scene.plots[11]=535,612,172
holywars.town-scene.plots[12]=500,352,201
holywars.town-scene.plots[13]=774,813,172
holywars.town-scene.plots[14]=1129,792,172
