spring.datasource.url=jdbc:sqlite:${holywars.db:holy-wars.db}
spring.datasource.hikari.maximum-pool-size=1
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

holywars.town-scene.width=1200
holywars.town-scene.height=720
holywars.town-scene.plots[1]=600,330,140
holywars.town-scene.plots[2]=600,180,140
holywars.town-scene.plots[3]=520,520,140
holywars.town-scene.plots[4]=680,520,140
holywars.town-scene.plots[5]=400,250,140
holywars.town-scene.plots[6]=800,250,140
holywars.town-scene.plots[7]=380,420,140
holywars.town-scene.plots[8]=820,420,140
holywars.town-scene.plots[9]=715,118,140
holywars.town-scene.plots[10]=300,330,140
holywars.town-scene.plots[11]=900,330,140
holywars.town-scene.plots[12]=600,117,164
holywars.town-scene.plots[13]=250,560,140
holywars.town-scene.plots[14]=400,640,140
