package holywars.town;

public enum Building {
    TOWN_HALL, ACADEMY, BARRACKS, TRADING_PORT, SHIPYARD, WAREHOUSE, TAVERN, MUSEUM,
    PALACE, GOVERNORS_RESIDENCE, EMBASSY, TRADING_POST, WORKSHOP, HIDEOUT, TOWN_WALL, TEMPLE,
    FORESTERS_HOUSE, STONEMASON, GLASSBLOWER, ALCHEMISTS_TOWER, WINEGROWER,
    CARPENTER, ARCHITECTS_OFFICE, OPTICIAN, WINE_PRESS, FIREWORK_TEST_AREA
}
